### ISSUE TITLE
Publish to bower as angular-countdown

### ISSUE THREAD

**Issue by bendrucker** [bendrucker/angular-countdown#1]
@matiassingers I noticed you published something with this name to bower but the repo's no longer online. Mind [unregistering](http://bower.io/docs/creating-packages/#unregister) it so I can use that name?

**Comment by matiassingers** [comment]
@bendrucker of course, it should be unregistered now - let me know if you have any problems registering it now.

**Comment by bendrucker** [comment]
Awesome! Thank you so much!
