### ISSUE TITLE
Problem with unused library functions

### ISSUE THREAD

**Issue by hcvazquez** [bendrucker/angular-countdown#5]
My name is Hernan; with a group of colleagues we are conducting a research about unused code present in dependencies of JavaScript projects. We call this functions, UFF (Unused foreign functions). We found that in most projects there exist a great amount of UFF that are being included in the final bundle. 
 
In the case of angular-countdown (v 1.2.1) our tools detected approximately 856 unused function in dependencies. Removing those functions, the size of angular-countdown bundled could be reduced at least 57% (All tests passed). I’m attaching the reduced version of your project. 
[bundle(optimized).txt](https://github.com/bendrucker/angular-countdown/files/671187/bundle.optimized.txt)

 
I’ll be very grateful if you can answer me the following questions:
-Did you were aware of the existence of these unused functions in your projects?
-Do you think that this is a problem? 
-Do you think that can be useful a tool for deal with this kind of problem?

Thanks in advance.

Cheers,

**Comment by bendrucker** [comment]
Thanks but I'm not interested. If you want to publish this tool as open source I'm sure people will make use of it but I'm not interested in answering survey questions about code slimming.
