### ISSUE TITLE
Issue found when try to Re invoke timer.start() again

### ISSUE THREAD

**Issue by Toomavic** [bendrucker/angular-countdown#6]
In my project, I need to show timer every time user click on (start button)

But what happens is the timer is displayed only once. and it's not showing again even when I try to call timer.start()

**Comment by bendrucker** [comment]
Hi, I’m not actively working on this project. I’d be happy to review and merge a PR that addresses the behavior you mentioned.

**Comment by Toomavic** [comment]
So what should I do ?

**Comment by bendrucker** [comment]
Have a look at the code and propose a change. If it wasn't clear from my original comment, I don't plan to work on this entirely by myself. But I would be happy to review your changes and get them merged in.

**Comment by Toomavic** [comment]
Ok Thanks
